uvmf:
  environments:
    memaccess:
      agents:
      - initiator_responder: INITIATOR
        name: memaccess_in_agent_handle
        type: memaccess_in
      - initiator_responder: INITIATOR
        name: memaccess_out_agent_handle
        type: memaccess_out
      analysis_components:
      - name: predictor
        parameters: []
        type: memaccess_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      - name: memaccess_in_pkg
      - name: memaccess_out_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: scoreboard
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: memaccess_out_transaction
      subenvs: []
      tlm_connections:
      - driver: memaccess_in_agent_handle.monitored_ap
        receiver: predictor.analysis_export
        validate: 'True'
      - driver: predictor.expected_output_analysis_port
        receiver: scoreboard.expected_analysis_export
        validate: 'True'
      - driver: memaccess_out_agent_handle.monitored_ap
        receiver: scoreboard.actual_analysis_export
        validate: 'True'
