uvmf:
  util_components:
    "decode_predictor":
      type: "predictor"
      analysis_exports:
        - name: "analysis_export"
          type: "decode_in_transaction"
      analysis_ports:
        - name: "expected_output_analysis_port"
          type: "decode_out_transaction"
  environments:
    "decode" :
      imports:
      - name: lc3_prediction_pkg
      - name: decode_in_pkg
      - name: decode_out_pkg
      agents :
        - name: "decode_in_agent_handle"
          type: "decode_in"
          initiator_responder: "INITIATOR"
        - name: "decode_out_agent_handle"
          type: "decode_out"
          initiator_responder: "RESPONDER"
      analysis_components :
        - name: "predictor"
          type: "decode_predictor"
      scoreboards :
        - name: "scoreboard"
          sb_type: "uvmf_in_order_scoreboard"
          trans_type: "decode_out_transaction"
      tlm_connections :
        - driver:   "decode_in_agent_handle.monitored_ap"
          receiver: "predictor.analysis_export"
        - driver:   "predictor.expected_output_analysis_port"
          receiver: "scoreboard.expected_analysis_export"
        - driver:   "decode_out_agent_handle.monitored_ap"
          receiver: "scoreboard.actual_analysis_export"
        
        