uvmf:
  environments:
    "fetch" :
      imports:
        - name: "lc3_prediction_pkg"
        - name: "fetch_in_pkg"
      agents :
        - name: "agent_fetch_in" 
          type: "fetch_in"
          initiator_responder: "INITIATOR"
        - name: "agent_fetch_out" 
          type: "fetch_out"
          initiator_responder: "INITIATOR"
      analysis_components :
        - name: "pred"
          type: "fetch_predictor"
    #  existing_library_component: 'True'
      scoreboards : 
        - name: "fetch_sb"
          sb_type: "uvmf_in_order_scoreboard"
          trans_type: "fetch_out_transaction"
      tlm_connections :
        - driver:   "agent_fetch_in.monitored_ap"
          receiver: "pred.analysis_export"
          validate: "True"
        - driver:   "pred.pred_out"
          receiver: "fetch_sb.expected_analysis_export"
          validate: "True"
        - driver:   "agent_fetch_out.monitored_ap"
          receiver: "fetch_sb.actual_analysis_export"
          validate: "True"
