uvmf:
  environments:
    fetch:
      agents:
      - initiator_responder: INITIATOR
        name: agent_fetch_in
        type: fetch_in
      - initiator_responder: INITIATOR
        name: agent_fetch_out
        type: fetch_out
      analysis_components:
      - name: pred
        parameters: []
        type: fetch_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      - name: fetch_in_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: fetch_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: fetch_out_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_fetch_in.monitored_ap
        receiver: pred.analysis_export
        validate: 'True'
      - driver: pred.pred_out
        receiver: fetch_sb.expected_analysis_export
        validate: 'True'
      - driver: agent_fetch_out.monitored_ap
        receiver: fetch_sb.actual_analysis_export
        validate: 'True'
